### ISSUE TITLE
Content fliesst hinter Footer

### ISSUE THREAD

**Issue by nwaldispuehl** [pfadiolten/pfadiolten-home#10]
Der Footer überdeckt den untersten Teil des Contents jeder Seite. Dies fällt beispielsweise auf der 'LeiterInnen'-Seite auf, wenn man nach ganz unten scrollt:

![2018-03-31_screenshot_leiter](https://user-images.githubusercontent.com/3245637/38167040-ed59ec10-352e-11e8-95da-64637863ce04.png)

**Comment by Veilyon** [comment]
Gefixt in 5a0b978412582da753591b6305bb311780d03373.
