### ISSUE TITLE
"Passwort vergessen" Option

### ISSUE THREAD

**Issue by Ar0rua** [pfadiolten/pfadiolten-home#13]
Ich vermisse im Anmeldefenster ein "Passwort vergessen"-Button. Cool wäre es, wenn es eine Möglichkeit gibt, selbständig sein Passwort zurück zu setzen oder zumindest ein Hinweis darauf, an wen man sich wenden soll.

**Comment by Veilyon** [comment]
Vorerst wird nur ein Hinweis angezeigt (8bbafee3c58900aa18eec23d278015d1fd67b5ef).
Die Account/Login-Implementation soll später mit der der NextCloud vereint werden, deshalb wird daran vorerst nichts grösseres mehr geändert.
