### ISSUE TITLE
Formatierungsfehler bei Aufzählungszeichen

### ISSUE THREAD

**Issue by Ar0rua** [pfadiolten/pfadiolten-home#14]
![formatierung mit aufzahlungszeichen](https://user-images.githubusercontent.com/39805901/40796904-0eaeb8e0-64f6-11e8-93e8-ea4c43aa0b15.PNG)

Aufzählungszeichen werden nach dem Speichern des Textes am linken Rand angezeigt anstatt direkt neben dem Text (siehe Bild), passiert aber nur wenn Text zentriert ausgerichtet ist, bei linker Ausrichtung ist alles OK.

**Comment by daniel-va** [comment]
Ist gefixt auf https://dev.pfadiolten.ch.
