### ISSUE TITLE
Aktivitäten: "Abmelden"-Knopf: Subject und Body vorausfüllen

### ISSUE THREAD

**Issue by nwaldispuehl** [pfadiolten/pfadiolten-home#17]
Der `Abmelden`-Knopf bei den Aktivitäten öffnet eine leere Mail. Als generell fauler Mensch wäre es für mich komfortabel, wenn die Mail bereits einigermassen vorausgefüllt wäre, z.B.:
> **Subject:** [Pfadi Olten] Abmeldung von `%AKTIVITÄT` (`%STUFE`) vom `%DATUM`
> **Body:** Liebe/r `%LEITER/IN`, ich kann leider nicht kommen...

Dies könnte relativ einfach mit paar Parametern realisiert werden:
```
mailto:leiter@pfadiolten.ch?subject=Abmeldung...&body=Liebe/r...
```

**Comment by Veilyon** [comment]
Implementiert in 1503f3586f4f9d565a032baa82841ee79e6a9b6e.

**Comment by nwaldispuehl** [comment]
Es funktioniert leider noch nicht wie gewünscht; ich könnte mir vorstellen, dass URL-fremden Zeichen codiert werden sollten. 

Was in meiner Mail erscheint:
> Liebe/r Pyro
>
> Ich kann leider nicht kommen

**Comment by Veilyon** [comment]
Das Problem liegt wahrscheinlich daran, dass ich die noch auszufüllenden Felder in `<...>` gewrappt habe. Je nach OS/Mailprogramm werden diese angezeigt, andere versuchen diese als HTML zu interpretieren:
![mail](https://user-images.githubusercontent.com/15192000/41398160-c1b0d214-6fb6-11e8-9322-61e62855060d.png)

Ich werde das bei Gelegenheit fixen, wahrscheinlich mit `{...}` statt `<...>`

**Comment by Veilyon** [comment]
Das Problem ist in feeb26f30a5ca0c551ddfcb49449849af965cde1 gelöst.
Der Fix wird mit dem Rest von [feature-boostrap4](/pfadiolten/pfadiolten-home/tree/feature-bootstrap4) live gehen.
