### ISSUE TITLE
Reiter (Tabs)

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#2]
Kalender umbenennen zu Agenda.
Leiter umbenennen zu LeiterInnen.

Ich denke,
**Artikel, Agenda, Schnuppern, Kontakt, LeiterInnen, Stufen Alben**
würde noch Sinn machen

**Comment by Veilyon** [comment]
angepasst in 0c72f3d35d310f970a1f9605e2ea5cca38d52fd9.
