### ISSUE TITLE
Anschlagskasten bei Stufen

### ISSUE THREAD

**Issue by theova** [pfadiolten/pfadiolten-home#20]
Ich finde den Anschlagskasten bei den Stufen super!

Um für neue Eltern klar zu machen, was das genau bedeutet, würde ich noch einen kurzen Titel schreiben, z.B. "nächste Aktivität".

**Comment by daniel-va** [comment]
Ist implementiert, live auf https://dev.pfadiolten.ch seit d7c7e9a99dc0fceb480d0e1ddf18cb27f4469e4b.
