### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by theova** [pfadiolten/pfadiolten-home#21]
Beim Kontakt würde ich zum einen die allgemeine info-Mailadresse reintun.
Z.B. Für allgemeine Fragen: info@...

Und dann fehlt noch Stracciatella.

**Comment by Veilyon** [comment]
Beides hinzugefügt in 0cdbefda045eb9f884c4469ca9a15ff5b3c8d2d2.
Wird beim nächsten Release auf https://dev.pfadiolten.ch dabei sein.

**Comment by theova** [comment]
Super. Habe noch das Geschlecht angepasst in 583a451.
