### ISSUE TITLE
Reiter "Verein" 

### ISSUE THREAD

**Issue by theova** [pfadiolten/pfadiolten-home#24]
Zwischen "Alben" und "Kontakt" soll ein Reiter "Verein" hinzugefügt werden. Darauf sollen unter anderem sein:
- Vorstellen des Vorstandes inkl. Fotos und Aufgabenbereich
- Hinweis auf den und Aufgaben des APV/HV

Nach Absprache mit unserem Vorstand, wäre es gut, wenn dieser Reiter bis Ende Jahr erstellt werden kann.

**Comment by theova** [comment]
Ich habe noch zwei kleinere Bugs gefunden:
* Ich kann keinen Verein löschen. Es erscheint die Meldung _The page you were looking for doesn't exist_.
* Die Vereine sind alphabetisch geordnet, aber _Pfadi Olten_ sollte zuoberst erscheinen.

**Comment by daniel-va** [comment]
Verein löschen funktioniert jetzt.
Auf der Vereins-Seite kann man neu auch ordnen, wie bei den Stufen.

+ bei Vereinsmitgliedern, die bereits als Benutzer hinterlegt sind, wird jetzt automatisch das Profilbild im Verein angezeigt.
