### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by daniel-va** [pfadiolten/pfadiolten-home#28]
Der Release v1.1.0 ist von meiner Seite aus releasebereit.
Er läuft auf https://dev.pfadiolten.ch mit einem Duplikat der produktiven Datenbank,
der jetzige Commit ist d14b3ee9e2c73c5a22ec92e02465195f7a1f5027.

Hauptfeatures des Releases sind:
- allgemeines Redesign
- `Vereine`-Kategorie

Soweit ich geprüft habe, funktioniert alles, und wird sowohl auf Desktops wie auch auf Mobiles richtig angezeigt. Sollten jetzt keine dringenden Änderungen mehr anfallen, würde ich vorschlagen, die Version produktiv zu nehmen.

**Comment by theova** [comment]
Sehr cool! :-)

Kann ich zuerst noch den Inhalt zum "Vereine" machen? Dann passt es für mich :-)

**Comment by daniel-va** [comment]
https://dev.pfadiolten.ch benutzt eine andere Datenbank als die produktive Website.
Du kannst Vereine also erst erfassen wenn die produktive Website mit dem neuen Release läuft.

**Comment by theova** [comment]
Ich werde den Text zuerst auf https://dev.pfadiolten.ch fertigstellen und mit dem Vorstand absprechen. 
Die Texte muss man dann halt kopieren.

Ich melde mich für die definitive Freigabe.

**Comment by theova** [comment]
Die definitive Freigabe ist da :tada: 

Danke für Deinen Einsatz!

**Comment by daniel-va** [comment]
Der Release ist jetzt live.
Die Vereine müssen aber noch manuell rüberkopiert werden.

**Comment by theova** [comment]
>  Die Vereine müssen aber noch manuell rüberkopiert werden.

Mach ich :+1:
