### ISSUE TITLE
Anonymisieren der Personen

### ISSUE THREAD

**Issue by theova** [pfadiolten/pfadiolten-home#29]
Rückmeldung aus dem Vorstand:
>Aufgefallen ist mir folgendes bei der Vorstellung der Leiter, bei jedem steht der Zivile Name. Dies ermöglicht es die Personen sehr leicht über Google ausfindig zu machen (und auch dessen Umfeld!). Konkret meine ich damit (wieder schwarzmalerei von mir…): Falls mal aus irgendeinem Grund ein Journalist Informationen über ein Pfadimitglied sucht, dann hat er auf unserer Homepage einen Jackpot, d.h. die gesuchte Person und alle Mitleiter namentlich mit Foto… alles sehr leicht über google auffindbar...

Ich und Frizzante haben den Vorschlag diskutiert, und finden es sinnvoll, alle Personen mit Ausnahme von Abteilungsleitung und Präsidenten der Vereine nur mit Pfadinamen aufzuführen.

Könnt  ihr dies software-mässig lösen?

(Von uns aus muss #28 nicht auf diesen Issue warten.)

**Comment by daniel-va** [comment]
Ist live.
