### ISSUE TITLE
Fotos in Fliesstext

### ISSUE THREAD

**Issue by theova** [pfadiolten/pfadiolten-home#31]
Es scheint mir zur Zeit nich möglich, ein Bild hochzuladen und im Lauftext zu integrieren.

Ich mache es so:
- Verein -> Pfadi Olten -> bearbeiten
- in Beschreibung/HTML Editor auf das Bild ("Grafik") klicken.
- "Grafik einfügen"
- "Wählen Sie eine Datei aus"
-" Choose Files" --> Bild mit ca. 750KB auswählen.

Es erscheint in der Vorschau, aber nicht in der gespeicherten Website.

**Comment by daniel-va** [comment]
Funktioniert jetzt per Drag&Drop.
