### ISSUE TITLE
Reiter: Kontakt

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#4]
Eigenständiger Reiter mit dem Namen "Kontakt".

Inhalt:
- Name und Kontakt des/der AbteilungsleiterIn.
- Adresse und kleiner Plan (am besten openstreetmaps.org) für die Pfadiheime.
- kurze Satz bezüglich Vermietung des Pfadiheims

**Comment by Veilyon** [comment]
Implementiert in 3cc731c915ea49c0306febfb24dbcb0b5e3afe4b.

Feature ist live. Für etwaige weitere Anpassungen bezüglich Kontakten bitte ein neues Issue erstellen.

**Comment by theova** [comment]
Super :-) mit OSM <3
Danke!
