### ISSUE TITLE
Kalender: Legende

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#5]
Klar machen, welche Farbe im Kalender was bedeutet.
Z.B mit einer Legende oder mit direktem Text im Kalender.

**Comment by Veilyon** [comment]
Welche Farben meinst du hier?
Der Kalender selbst beinhaltet nur 3 Farben:
* hellgrau 
> normaler Tag
* dunkelgrau
> Tag, der nicht zum ausgewählten Monat gehört, aber zur Vervollständigung der Woche angezeigt wird
* gelb
> jetziger Tag

Diese Farben sind relativ selbsterklärend, und auch in fast jedem anderen Kalender vorzufinden - meist ohne Legende. 

Die eigentliche Implementierung einer solchen Legende ist keine grosse Sache, mir stellt sich eher die Frage, ob diese wirklich nötig ist. Oder meinst du andere Farben?

**Comment by theova** [comment]
Stimmt, du hast recht.
Als er noch leer war, dachte ich hellgrau steht für Ferien oder so....

Keine Legende nötig.
