### ISSUE TITLE
Kann Aktivität nicht bearbeiten

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#6]
Ich kann nach dem erstellen einer Aktivität diese später nicht mehr bearbeiten (z.B. Skiweekend II).

**Comment by Veilyon** [comment]
Problem tritt für mich nicht auf (konnte u. A. Skiweekend II bearbeiten).
Getestet sowohl auf meinem und deinem Account.

Kannst du nochmals probieren, ob es jetzt funktioniert?

**Comment by Veilyon** [comment]
Falls dein Problem war, dass der Link zum bearbeiten nicht immer funktioniert, sollte dies nun auch behoben sein (79880fe447c89128b4416c955c90107525111be6).

**Comment by theova** [comment]
Funktioniert immer noch nicht. Konkret drücke ich auf den Schreiber (https://pfadiolten.webtest.oetiker.ch/kalender/5/aktivitaeten/bearbeiten).

Browser: Mozilla Firefox 58.0.2

**Comment by Veilyon** [comment]
Kannst du das ganze nochmals probieren?
Der Fix (79880fe) ist erst seit heute live.

**Comment by theova** [comment]
Kann keine Aktivität mehr erstellen...
Die Buttons unter https://pfadiolten.webtest.oetiker.ch/agenda/erfassen funktionieren nicht...

**Comment by Veilyon** [comment]
War ein Firefox-spezifischer Bug (unendlicher Loop in JavaScript).
Sollte jetzt gefixt sein.

Bitte prüfen und Issue schliesen, falls alles funktioniert.

**Comment by theova** [comment]
Funktioniert jetzt. Danke!
