### ISSUE TITLE
Text bearbeitung

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#8]
Knopf für Hyperlinks fehlt.

Rechtschreibeprüfung wäre super!

**Comment by Veilyon** [comment]
Hyperlinks hinzugefügt in e736ffbaac1664bebb1809dcb719234c815a094e.

Rechtschreibeprüfung wird eventuell später hinzugefügt, ist zurzeit aufgrund technischer Schwierigkeiten jedch kein Hauptziel.
