### ISSUE TITLE
Aktuelles

### ISSUE THREAD

**Issue by Gruenblau** [pfadiolten/pfadiolten-home#9]
Wie kann ich Text/Bilder unter "Aktuelles" erscheinen lassen?

**Comment by Veilyon** [comment]
Gepinnte Artikel werden als Aktuell erscheinen.
Alben bieten kein solches Feature an.

**Comment by Gruenblau** [comment]
Vorschlag: Angepinnt umbenennen zu "unter Aktuelles erscheinen"

**Comment by Veilyon** [comment]
angepasst in 0c72f3d35d310f970a1f9605e2ea5cca38d52fd9.
